---
openapi: 3.0.0
info:
  title: Stock Market API
  description: "This API allows you place orders on the stock market, and track your stocks that you have bought"
  contact:
    email: vsomera77@outlook.com
  version: 1.0.0
servers:
- url: /
tags:
- name: stockbroker
  description: Operations available to stockbrokers
- name: trader
  description: Operations available to traders
paths:
  /api/orders:

    # post:
    #   tags:
    #   - trader
    #   summary: Allows users to place buy or sell orders for a stock
    #   description: places buy or sell order at a stock's market price
    #   operationId: app.placeMarketOrder
    #   requestBody:
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Orders'
    #   responses:
    #     "201":
    #       description: Market order placed
    #     "400":
    #       description: "invalid input, object invalid"
    
    get:
      tags:
      - trader
      operationId: app.getOrders
      description : gets all orders placed by the user
      parameters:
        - name : timestamp
          in : query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description : Successfully returned a list of placed orders
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Orders'
  /api/stocks:

    # post:
    #   tags:
    #   - trader
    #   summary: Adds a stock to a user's list of bought stocks to track
    #   description: adds new stock to track
    #   operationId: app.addStockToList
    #   requestBody:
    #     description: Sells a stock at the current market price
    #     content:
    #       application/json:
    #         schema:
    #           $ref: '#/components/schemas/Stocks'
    #   responses:
    #     "201":
    #       description: Stock added to Watch list
    #     "400":
    #       description: "invalid input, object invalid"
    
    get:
      tags:
      - trader
      operationId: app.getStocks
      description : gets all orders placed by the user
      parameters:
        - name : timestamp
          in : query
          description: Limits the number of items on a page
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
      responses:
        '200':
          description : Successfully returned a list of stocks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Stocks'    
                  
components:
  schemas:
    Orders:
      required:
      - order_type
      - price
      - quantity
      - stock_id
      - trace_id
      type: object
      properties:
        stock_id:
          type: string
          example: APPL
        order_type:
          type: string
          example: Buy || Sell
        quantity:
          type: integer
          example: 5
        price:
          type: number
        trace_id:
          type: string
          example: aabbccdd-1234-5678-90ab-cdef01234567 
    Stocks:
      required:
      - name
      - purchase_price
      - quantity
      - symbol
      - trace_id
      type: object
      properties:
        symbol:
          type: string
          example: APPL
        name:
          type: string
          example: APPL Inc.
        quantity:
          type: integer
          example: 5
        purchase_price:
          type: number
        trace_id:
          type: string
          example: aabbccdd-1234-5678-90ab-cdef01234567 
